server:
  port: 10000

com:
  profile:
    external:
      base-url: https://jsonplaceholder.typicode.com/users/

spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    url: jdbc:postgresql://localhost:5432/TESTDB
    user: postgres
    password: postgres
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    schemas: profile
  datasource:
    url: jdbc:postgresql://localhost:5432/TESTDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
      idleTimeout: 300000
      maximumPoolSize: 30
      minimumIdle: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: profile
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    com:
      profile: DEBUG